function [trackDat, expmt, props] = multiTrack(props, trackDat, expmt)

props = erodeDoubleBlobs(props, trackDat);

% apply area threshold before assigning centroids
above_min = cat(1,props.Area) .* (expmt.parameters.mm_per_pix^2) > ...
    expmt.parameters.area_min;
props(~above_min,:) = [];

[candidate_ROI_cen, blob_num] = assignROI(cat(1,props.Centroid), expmt);

[trackDat.traces, blob_assigned, blob_permutation] = ...
        cellfun(@(x,y) sortROI_multitrack(x, y, ...
                trackDat.tPrev, expmt.parameters.speed_thresh), ...
                trackDat.traces, candidate_ROI_cen, 'UniformOutput',false);
            
trackDat.traces = ...
    cellfun(@(t) updateTraceDuration(t, expmt.parameters.max_trace_duration), ...
                       trackDat.traces, 'UniformOutput', false);
            
trackDat.permutation = cellfun(@(bn,bp) bn(bp), blob_num, blob_permutation,...
                    'UniformOutput',false);

[trackDat.traces] = cellfun(@(x,y,z) deleteLostTraces(x), ...
        trackDat.traces, 'UniformOutput', false);

unassigned_blobs = cellfun(@(x,y) x(~y,:), candidate_ROI_cen, ... 
                       blob_assigned, 'UniformOutput', false);

[trackDat.candidates, blob_assigned, ~] = ...
    cellfun(@(x,y) sortROI_multitrack(x, y, trackDat.tPrev, ...
            expmt.parameters.speed_thresh), trackDat.candidates,...
            unassigned_blobs,'UniformOutput', false);  

trackDat.candidates = ...
    cellfun(@(t) updateTraceDuration(t, expmt.parameters.max_trace_duration), ...
                       trackDat.candidates, 'UniformOutput', false);

[new_traces, trackDat.candidates] = cellfun(@(x,y,ba) getNewTraces(x, y, ba, ...
                  expmt.parameters.max_trace_duration, trackDat.t),...
                  unassigned_blobs, trackDat.candidates, blob_assigned,...
                  'UniformOutput', false);

trackDat.traces = cellfun(@(x,t) ...
    addNewTraces(x,t,expmt.parameters.max_trace_duration, ...
          trackDat.t), new_traces, trackDat.traces, 'UniformOutput', false);
